drop view ctmv6_stats_log;
create view ctmv6_stats_log as
select datein tran_dt, 'registration' action, carrier, count(1) prepaid, 0 postpaid, 0 tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'GLOBE' and brand='PREPAID' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, count(1) postpaid, 0 tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'GLOBE' and brand='POSTPAID' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, 0 postpaid, count(1) tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'GLOBE' and brand='TM' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, 0 postpaid, 0 tm_tnt, count(1) tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'GLOBE' and brand='TATTOO' group by datein, carrier, country union
select datein, 'registration' action, carrier, count(1) prepaid, 0 postpaid, 0 tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'SMART' and brand='PREPAID' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, count(1) postpaid, 0 tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'SMART' and brand='POSTPAID' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, 0 postpaid, count(1) tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'SMART' and brand='TNT' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, 0 postpaid, 0 tm_tnt, count(1) tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'SMART' and brand='BRO' group by datein, carrier, country union
select datein, 'registration' action, carrier, count(1) prepaid, 0 postpaid, 0 tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'SUN' and brand='PREPAID' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, count(1) postpaid, 0 tm_tnt, 0 tattoo_bro, 0 others, country from ctmv6_staging_stats where action = 'msisdn_registration' and carrier = 'SUN' and brand='POSTPAID' group by datein, carrier, country union
select datein, 'registration' action, carrier, 0 prepaid, 0 postpaid, 0 tm_tnt, 0 tattoo_bro, count(1) others, country from ctmv6_staging_stats where action = 'msisdn_registration' and brand='ALL' group by datein, carrier, country union
select datein, 'registration' action, source, 0 prepaid, 0 postpaid, 0 tm_tnt, 0 tattoo_bro, count(1) others, '' country from ctmv6_staging_stats where action = 'sn_registration' group by datein, source union

select tran_dt, type action, upper(carrier), pre prepaid, post postpaid, tm_tnt, tat_bro, others, upper(carrier) country from ctmv6_stats_csg;


select CASE WHEN source='ios' then 'iOS'
            WHEN source='web' then 'Web'
            WHEN source='an-' then 'Android'
            ELSE 'Others'
       END as c_source, count(1)
from ctmv6_staging_stats
where action = 'login' group by 1 limit 10;


drop view ctmv6_stats_dtl;
create view ctmv6_stats_dtl as
select tran_dt, action, country, carrier, 
       sum(prepaid) prepaid, 
       sum(postpaid) postpaid, 
       sum(tm_tnt) tm_tnt, 
       sum(tattoo_bro) tattoo_bro, 
       sum(others) others, 
       sum(prepaid+postpaid+tm_tnt+tattoo_bro+others) total 
from ctmv6_stats_log as t1 group by tran_dt, carrier, action, country;


drop view ctmv6_stats_daily;
create view ctmv6_stats_daily as
select 0 seq_no, tran_dt, concat('CTMv6 Stats as of ', date_format(tran_dt, '%b %d,%Y')) stats from ctmv6_stats_dtl where action='registration' group by tran_dt union
select 1, tran_dt, '' stats from ctmv6_stats_dtl where action = 'registration' group by tran_dt union
select 2 seq_no, tran_dt, 'REGISTRATION' stats from ctmv6_stats_dtl where action='registration' group by tran_dt union
select 3, tran_dt, concat(carrier, ': ', total,'
   Pre: ', prepaid, '
   Post: ', postpaid, '
   TNT: ', tm_tnt, '
   BRO: ', tattoo_bro) stats from ctmv6_stats_dtl where carrier='SMART' and action = 'registration' union
select 4, tran_dt, concat(carrier, ': ', total,'
   Pre: ', prepaid, '
   Post: ', postpaid, '
   TM: ', tm_tnt, '
   Tattoo: ', tattoo_bro) stats from ctmv6_stats_dtl where carrier='GLOBE' and action = 'registration' union
select 5, tran_dt, concat(carrier, ': ', total,'
   Pre: ', prepaid, '
   Post: ', postpaid) stats from ctmv6_stats_dtl where carrier='SUN' and action = 'registration' union
select 6, tran_dt, concat(carrier, ': ', total) stats from ctmv6_stats_dtl where carrier not in ('SUN', 'SMART', 'GLOBE') and action = 'registration'
;



CREATE TABLE ctmv6_stats_dtl (
  tran_dt date NOT NULL,
  carrier varchar(30) NOT NULL,
  type varchar(30) NOT NULL,
  post int(8) NOT NULL DEFAULT 0,
  pre int(8) NOT NULL DEFAULT 0,
  tm_tnt int(8) NOT NULL DEFAULT 0,
  tat_bro int(8) NOT NULL DEFAULT 0,
  others int(8) NOT NULL DEFAULT 0,
  total int default 0,
  PRIMARY KEY (tran_dt,carrier,type)
);

insert into ctmv6_stats_csg values ('2014-01-07', 'globe', 'hits', 12280,  48221,   9743, 0, 0,  70244);
insert into ctmv6_stats_csg values ('2014-01-07', 'globe', 'uniq_charged',  4127,  15866,   3795, 0, 0,  23788);
insert into ctmv6_stats_csg values ('2014-01-07', 'globe', 'uniq_nonreg',  1322,  78463,   5788, 0, 0,  85573);
insert into ctmv6_stats_csg values ('2014-01-07', 'globe', 'mt', 56978, 305307, 133976, 0, 0, 496261);
insert into ctmv6_stats_csg values ('2014-01-07', 'smart', 'hits',  4768,  56854,  23268, 0, 0,  84890);
insert into ctmv6_stats_csg values ('2014-01-07', 'smart', 'uniq_charged',  1716,  17272,   7843, 0, 0,  26831);
insert into ctmv6_stats_csg values ('2014-01-07', 'smart', 'uniq_nonreg',   346, 104881,  13233, 0, 0, 118460);
insert into ctmv6_stats_csg values ('2014-01-07', 'smart', 'mt', 23962, 441919, 309675, 0, 0, 775556);
insert into ctmv6_stats_csg values ('2014-01-07', 'sun', 'hits',  3739,  10290,      0, 0, 0,  14029);
insert into ctmv6_stats_csg values ('2014-01-07', 'sun', 'uniq_charged',  1620,   3586,      0, 0, 0,   5206);
insert into ctmv6_stats_csg values ('2014-01-07', 'sun', 'uniq_nonreg',   182,  27636,      0, 0, 0,  27818);
insert into ctmv6_stats_csg values ('2014-01-07', 'sun', 'mt', 23362, 106095,      0, 0, 0, 129457);


create view ctmv6_stat_log as
select tran_dt, total gl_hits_total, post gl_hits_post, pre gl_hits_pre, tm_tnt gl_hits_tm, greatest(total-(post+pre+tm_tnt),0) gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='globe' and type='hits' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, total gl_uniq_total, post gl_uniq_post, pre gl_uniq_pre, tm_tnt gl_uniq_tm, greatest(total-(post+pre+tm_tnt),0) gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='globe' and type='uniq_charged' union
select tran_dt, total gl_hits_total, post gl_hits_post, pre gl_hits_pre, tm_tnt gl_hits_tm, greatest(total-(post+pre+tm_tnt),0) gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='globe' and type='free' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, total gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='globe' and type='uniq_nonreg' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, total gl_reg_total, post gl_reg_post, pre gl_reg_pre, tm_tnt gl_reg_tm, greatest(total-(post+pre+tm_tnt),0) gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='globe' and type='reg_carrier' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, total sm_hits_total, post sm_hits_post, pre sm_hits_pre, tm_tnt sm_hits_tm, greatest(total-(post+pre+tm_tnt),0) sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro, 0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='smart' and type='hits' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, total sm_uniq_total, post sm_uniq_post, pre sm_uniq_pre, tm_tnt sm_uniq_tm, greatest(total-(post+pre+tm_tnt),0) sm_uniq_bro, 0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='smart' and type='uniq_charged' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro, total sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='smart' and type='uniq_nonreg' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro, 0 sm_uniq_nonreg, total sm_reg_total, post sm_reg_post, pre sm_reg_pre, tm_tnt sm_reg_tm, greatest(total-(post+pre+tm_tnt),0)  sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='smart' and type='reg_carrier' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, total su_hits_total, post su_hits_post, pre su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre, 0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='sun' and type='hits' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, total su_uniq_total, post su_uniq_post, pre su_uniq_pre, 0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='sun' and type='uniq_charged' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre, total su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='sun' and type='uniq_nonreg' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro,0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre, 0 su_uniq_nonreg, total su_reg_total, post su_reg_post, pre su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='sun' and type='reg_carrier' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, total gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='globe' and type='reg_carrier' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, total sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='smart' and type='reg_carrier' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, total sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='sun' and type='reg_carrier' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, total fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='facebook' and type='reg_sn' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, total tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='twitter' and type='reg_sn' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, total go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='googleplus' and type='reg_sn' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, total li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='linkedin' and type='reg_sn' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, others an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='android' and type='login' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, others ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='ios' and type='login' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, others web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='web' and type='login' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, total reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='AUSTRALIA' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, total reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='CANADA' and type='reg_country' union 
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, total reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='CHINA' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, total reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='HONG KONG' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, total reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='JAPAN' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, total reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='MALAYSIA' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, total reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='PHILIPPINES' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, total reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='QATAR' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, total reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='SAUDI ARABIA' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, total reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='SINGAPORE' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, total reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='SOUTH KOREA' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, total reg_uae, 0 reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='UAE' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, total reg_united_kingdom, 0 reg_united_states from ctmv6_stats_dtl where carrier='UNITED KINGDOM' and type='reg_country' union
select tran_dt, 0 gl_hits_total, 0 gl_hits_post, 0 gl_hits_pre, 0 gl_hits_tm, 0 gl_hits_bro, 0 gl_uniq_total, 0 gl_uniq_post, 0 gl_uniq_pre, 0 gl_uniq_tm, 0 gl_uniq_bro, 0 gl_uniq_nonreg, 0 gl_reg_total, 0 gl_reg_post, 0 gl_reg_pre, 0 gl_reg_tm, 0 gl_reg_bro, 0 sm_hits_total, 0 sm_hits_post, 0 sm_hits_pre, 0 sm_hits_tm, 0 sm_hits_bro, 0 sm_uniq_total, 0 sm_uniq_post, 0 sm_uniq_pre, 0 sm_uniq_tm, 0 sm_uniq_bro,0 sm_uniq_nonreg, 0 sm_reg_total, 0 sm_reg_post, 0 sm_reg_pre, 0 sm_reg_tm, 0 sm_reg_bro, 0 su_hits_total, 0 su_hits_post, 0 su_hits_pre, 0 su_uniq_total, 0 su_uniq_post, 0 su_uniq_pre,0 su_uniq_nonreg, 0 su_reg_total, 0 su_reg_post, 0 su_reg_pre, 0 gl_reg_carrier, 0 sm_reg_carrier, 0 sn_reg_carrier, 0 fb_reg_sn, 0 tw_reg_sn, 0 go_reg_sn, 0 li_reg_sn, 0 gl_login, 0 sm_login, 0 su_login, 0 an_login, 0 ios_login, 0 web_login, 0 reg_australia, 0 reg_canada, 0 reg_china, 0 reg_hong_kong, 0 reg_japan, 0 reg_malaysia, 0 reg_philippines, 0 reg_qatar, 0 reg_saudi_arabia, 0 reg_singapore, 0 reg_south_korea, 0 reg_uae, 0 reg_united_kingdom, total reg_united_states from ctmv6_stats_dtl where carrier='UNITED STATES' and type='reg_country'
;
 

create view ctmv6_stat_summary as
select tran_dt, sum(gl_hits_total) gl_hits_total, sum(gl_hits_post) gl_hits_post, sum(gl_hits_pre) gl_hits_pre, sum(gl_hits_tm) gl_hits_tm, sum(gl_hits_bro) gl_hits_bro, sum(gl_uniq_total) gl_uniq_total, sum(gl_uniq_post) gl_uniq_post, sum(gl_uniq_pre) gl_uniq_pre, sum(gl_uniq_tm) gl_uniq_tm, sum(gl_uniq_bro) gl_uniq_bro, sum(gl_uniq_nonreg) gl_uniq_nonreg, sum(gl_reg_total) gl_reg_total, sum(gl_reg_post) gl_reg_post, sum(gl_reg_pre) gl_reg_pre, sum(gl_reg_tm) gl_reg_tm, sum(gl_reg_bro) gl_reg_bro, sum(sm_hits_total) sm_hits_total, sum(sm_hits_post) sm_hits_post, sum(sm_hits_pre) sm_hits_pre, sum(sm_hits_tm) sm_hits_tm, sum(sm_hits_bro) sm_hits_bro, sum(sm_uniq_total) sm_uniq_total, sum(sm_uniq_post) sm_uniq_post, sum(sm_uniq_pre) sm_uniq_pre, sum(sm_uniq_tm) sm_uniq_tm, sum(sm_uniq_bro) sm_uniq_bro, sum(sm_uniq_nonreg) sm_uniq_nonreg, sum(sm_reg_total) sm_reg_total, sum(sm_reg_post) sm_reg_post, sum(sm_reg_pre) sm_reg_pre, sum(sm_reg_tm) sm_reg_tm, sum(sm_reg_bro) sm_reg_bro, sum(su_hits_total) su_hits_total, sum(su_hits_post) su_hits_post, sum(su_hits_pre) su_hits_pre, sum(su_uniq_total) su_uniq_total, sum(su_uniq_post) su_uniq_post, sum(su_uniq_pre) su_uniq_pre, sum(su_uniq_nonreg) su_uniq_nonreg, sum(su_reg_total) su_reg_total, sum(su_reg_post) su_reg_post, sum(su_reg_pre) su_reg_pre, 
       sum(gl_reg_carrier) gl_reg_carrier, sum(sm_reg_carrier) sm_reg_carrier, sum(sn_reg_carrier) sn_reg_carrier, sum(fb_reg_sn) fb_reg_sn, sum(tw_reg_sn) tw_reg_sn, sum(go_reg_sn) go_reg_sn, sum(li_reg_sn) li_reg_sn, 
       sum(gl_login) gl_login, sum(sm_login) sm_login, sum(su_login) su_login, sum(an_login) an_login, sum(ios_login) ios_login, sum(web_login) web_login,
       sum(reg_australia) reg_australia, sum(reg_canada) reg_canada, sum(reg_china) reg_china, sum(reg_hong_kong) reg_hong_kong, sum(reg_japan) reg_japan, sum(reg_malaysia) reg_malaysia, sum(reg_philippines) reg_philippines, sum(reg_qatar) reg_qatar, sum(reg_saudi_arabia) reg_saudi_arabia, sum(reg_singapore) reg_singapore, sum(reg_south_korea) reg_south_korea, sum(reg_uae) reg_uae, sum(reg_united_kingdom) reg_united_kingdom, sum(reg_united_states) reg_united_states
from ctmv6_stat_log group by tran_dt
;

delimiter //

CREATE FUNCTION sf_msisdn_country(in_msisdn_id varchar(30)) returns varchar(30) DETERMINISTIC
BEGIN
   DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET @errno = 1;
   IF left(in_msisdn_id,2) = '63' then
     SET @msisdn_country = 'PHILIPPINES';
   ELSEIF in_msisdn_id is not null then
     SELECT operator 
     INTO   @msisdn_country
     FROM   mobile_pattern
     WHERE  in_msisdn_id REGEXP pattern limit 1;
   ELSE
     SET @msisdn_country = NULL;
   END IF;
   RETURN @msisdn_country;
END;
//

delimiter ;



select reg_date, upper(rtrim('Australia           ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '61%' group by reg_date;
select reg_date, rtrim('Canada              '), count(1) from ctm_registration where msisdn like '1%' group by reg_date;
select reg_date, upper(rtrim('China               ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '86%' group by reg_date;
select reg_date, upper(rtrim('Hong Kong           ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '852%' group by reg_date;
select reg_date, upper(rtrim('Malaysia            ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '60%' group by reg_date;
select reg_date, upper(rtrim('Philippines         ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '63%' group by reg_date;
select reg_date, upper(rtrim('Qatar               ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '974%' group by reg_date;
select reg_date, upper(rtrim('Saudi Arabia        ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '966%' group by reg_date;
select reg_date, upper(rtrim('Singapore           ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '65%' group by reg_date;
select reg_date, upper(rtrim('South Korea         ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '82%' group by reg_date;
select reg_date, upper(rtrim('United Arab Emirates')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '971%' group by reg_date;
select reg_date, upper(rtrim('United Kingdom      ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '44%' group by reg_date;
select reg_date, upper(rtrim('United States       ')), 'reg_country', 0, 0, 0, 0, count(1) from ctm_registration where msisdn like '1%' group by reg_date; 

select reg_date, rtrim('Guam                '), count(1) from ctm_registration where msisdn like '1%' group by reg_date;


insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Nigeria             ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '234%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Greece              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '30%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('France              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '33%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Spain               ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '34%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Ireland             ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '353%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Italy               ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '39%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Sweden              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '46%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Norway              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '47%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Mexico              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '52%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Brazil              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '55%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Venezuela           ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '58%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('New Zealand         ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '64%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Thailand            ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '66%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Kazakhstan          ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '7%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Vietnam             ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '84%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('North Korea         ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '850%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Macau               ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '853%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Taiwan              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '886%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('India               ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '91%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Pakistan            ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '92%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Lebanon             ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '961%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Jordan              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '962%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Iraq                ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '964%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Kuwait              ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '965%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Oman                ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '968%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Bahrain             ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '973%' group by reg_date;
insert into ctmv6_stats_dtl select reg_date, upper(rtrim('Qatar               ')), 'reg_country', 0, 0, 0, 0, 0,count(1) from ctm_registration where msisdn like '974%' group by reg_date;


| 2014-02-27 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    19 |
| 2014-02-28 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    34 |
| 2014-03-01 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    35 |
| 2014-03-02 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    23 |
| 2014-03-03 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    29 |
| 2014-03-04 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    26 |
| 2014-03-05 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    19 |
| 2014-03-06 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    23 |
| 2014-03-07 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    20 |
| 2014-03-10 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    16 |
| 2014-03-11 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    14 |
| 2014-03-12 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    35 |
| 2014-03-13 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    18 |
| 2014-03-14 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    29 |
| 2014-03-15 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    21 |
| 2014-03-16 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    23 |
| 2014-03-17 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    22 |
| 2014-03-18 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    23 |
| 2014-03-19 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    18 |
| 2014-03-20 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    20 |
| 2014-03-21 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    28 |
| 2014-03-22 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    31 |
| 2014-03-23 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    30 |
| 2014-03-24 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    26 |
| 2014-03-25 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    15 |
| 2014-03-26 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    19 |
| 2014-03-27 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    15 |
| 2014-03-28 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    30 |
| 2014-03-29 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    29 |
| 2014-03-30 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    24 |
| 2014-03-31 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    24 |
| 2014-04-01 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    36 |
| 2014-04-02 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    24 |
| 2014-04-03 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    25 |
| 2014-04-04 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    25 |
| 2014-04-05 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    32 |
| 2014-04-06 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    28 |
| 2014-04-07 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    35 |
| 2014-04-08 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    25 |
| 2014-04-09 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    22 |
| 2014-04-10 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    19 |
| 2014-04-11 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    23 |
| 2014-04-12 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    37 |
| 2014-04-13 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    30 |
| 2014-04-14 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    15 |
| 2014-04-15 | QATAR   | reg_country |    0 |   0 |      0 |       0 |      0 |    31 |
