#!/usr/bin/perl

use warnings;
use lib "/home/dba_scripts/oist_stat/Lib";
use common;
use myconstants;
use DB;

use Spreadsheet::WriteExcel;
use MIME::Lite;

my $current_date = "";
my $current_day = "";

$current_date = $ARGV[0];
$current_day = $ARGV[1];
$txt_month = $ARGV[2];

my $excel_file = "/home/dba_scripts/oist_stat/ctmv6_stat_".$current_date.".xls";
print $excel_file;

my $dbh_ctmv6 = DB::DBconnect(myconstants::CTMV5_DB,myconstants::CTMV5_HOST,myconstants::CTMV5_USER,myconstants::CTMV5_PASSWORD);

# Create a new Excel workbook
my $workbook = Spreadsheet::WriteExcel->new($excel_file);

my $sth_ctm_v6;

$strSQLCTMv6 = "select DATE_FORMAT(tran_dt,'%m/%d/%Y'),  gl_hits_total, gl_hits_post, gl_hits_pre, gl_hits_tm, gl_hits_bro, gl_uniq_total, gl_uniq_post, gl_uniq_pre, gl_uniq_tm, gl_uniq_bro, gl_uniq_nonreg, gl_reg_total, gl_reg_post, gl_reg_pre, gl_reg_tm, gl_reg_bro, sm_hits_total, sm_hits_post, sm_hits_pre, sm_hits_tm, sm_hits_bro, sm_uniq_total, sm_uniq_post, sm_uniq_pre, sm_uniq_tm, sm_uniq_bro, sm_uniq_nonreg, sm_reg_total, sm_reg_post, sm_reg_pre, sm_reg_tm, sm_reg_bro, su_hits_total, su_hits_post, su_hits_pre, su_uniq_total, su_uniq_post, su_uniq_pre, su_uniq_nonreg, su_reg_total, su_reg_post, su_reg_pre, gl_reg_carrier, sm_reg_carrier, sn_reg_carrier, fb_reg_sn, tw_reg_sn, go_reg_sn, li_reg_sn, gl_login, sm_login, su_login, an_login, ios_login, web_login from ctmv6_stat_summary where left(tran_dt,7) = left(date_sub(curdate(), interval 1 day), 7)";

$sth_ctm_v6 = $dbh_ctmv6->prepare($strSQLCTMv6);
$sth_ctm_v6->execute();

# Add a worksheet
$worksheet = $workbook->add_worksheet($txt_month);


#  Add and define a format
$format = $workbook->add_format(bg_color => 'gray'); # Add a format
$format->set_bold();
$format->set_font('Calibri');
$format->set_size('9');
$format->set_color('black');
$format->set_align('center');
$format->set_border(2);

$format1 = $workbook->add_format(); # Add a format
#$format1->set_bold();
$format1->set_font('Calibri');
$format1->set_size('9');
$format1->set_color('black');
$format1->set_align('right');
$format1->set_border(1);

$format2 = $workbook->add_format(bg_color => 'yellow'); # Add a format
$format2->set_bold();
$format2->set_font('Calibri');
$format2->set_size('9');
$format2->set_color('black');
$format2->set_align('center');
$format2->set_border(2);

$format3 = $workbook->add_format(bg_color => 'green'); # Add a format
$format3->set_bold();
$format3->set_font('Calibri');
$format3->set_size('9');
$format3->set_color('black');
$format3->set_align('center');
$format3->set_border(2);

$format4 = $workbook->add_format(bg_color => 'green'); # Add a format
$format4->set_bold();
$format4->set_font('Calibri');
$format4->set_size('9');
$format4->set_color('black');
$format4->set_align('center');
$format4->set_border(2);

# Write a formatted and unformatted string, row and column notation.
$worksheet->merge_range('B2:Q2',   'GLOBE', $format2);
$worksheet->merge_range('S2:AH2',  'SMART', $format2);
$worksheet->merge_range('AJ2:AS2', 'SUN', $format2);
$worksheet->merge_range('AU2:BA2', 'REGISTRATION', $format2);
$worksheet->merge_range('BC2:BH2', 'LOGIN', $format2);

$worksheet->merge_range('B3:F3',   'HITS', $format3);
$worksheet->merge_range('G3:K3',   'Unique Charged', $format3);
$worksheet->write(2, 11, 'Unique Non-Reg', $format4);
$worksheet->merge_range('M3:Q3',   'Registration', $format3);

$worksheet->merge_range('S3:W3',   'HITS', $format3);
$worksheet->merge_range('X3:AB3',  'Unique Charged', $format3);
$worksheet->write(2, 28, 'Unique Non-Reg', $format4);
$worksheet->merge_range('AD3:AH3', 'Registration', $format3);

$worksheet->merge_range('AJ3:AL3', 'HITS', $format3);
$worksheet->merge_range('AM3:AO3', 'Unique Charged', $format3);
$worksheet->write(2, 41, 'Unique Non-Reg', $format4);
$worksheet->merge_range('AQ3:AS3', 'Registration', $format3);

$worksheet->merge_range('AU3:BA3', 'per Carrier or SN', $format3);
$worksheet->merge_range('BC3:BH3', 'Sign-in via', $format3);

$worksheet->set_column(0,10,8);
$worksheet->set_column(11,11,12);
$worksheet->set_column(12,16,8);
$worksheet->set_column(17,17,2);
$worksheet->set_column(18,27,8);
$worksheet->set_column(28,28,12);
$worksheet->set_column(29,33,8);
$worksheet->set_column(34,34,2);
$worksheet->set_column(35,40,8);
$worksheet->set_column(41,41,12);
$worksheet->set_column(42,43,8);
$worksheet->set_column(45,45,2);
$worksheet->set_column(46,52,8);
$worksheet->set_column(53,53,2);
$worksheet->set_column(54,70,8);

$row = 2;
$col = 0;
$i=1;

#GLOBE
$worksheet->write($row+$i, $col, 'DATE', $format);
$worksheet->write($row+$i, $col+1, 'TOTAL', $format);
$worksheet->write($row+$i, $col+2, 'Postpaid', $format);
$worksheet->write($row+$i, $col+3, 'Prepaid', $format);
$worksheet->write($row+$i, $col+4, 'TM', $format);
$worksheet->write($row+$i, $col+5, 'Tattoo', $format);
$worksheet->write($row+$i, $col+6, 'TOTAL', $format);
$worksheet->write($row+$i, $col+7, 'Postpaid', $format);
$worksheet->write($row+$i, $col+8, 'Prepaid', $format);
$worksheet->write($row+$i, $col+9, 'TM', $format);
$worksheet->write($row+$i, $col+10, 'Tattoo', $format);
$worksheet->write($row+$i, $col+11, 'TOTAL', $format);
$worksheet->write($row+$i, $col+12, 'TOTAL', $format);
$worksheet->write($row+$i, $col+13, 'Postpaid', $format);
$worksheet->write($row+$i, $col+14, 'Prepaid', $format);
$worksheet->write($row+$i, $col+15, 'TM', $format);
$worksheet->write($row+$i, $col+16, 'Tattoo', $format);
#SMART
$worksheet->write($row+$i, $col+18, 'TOTAL', $format);
$worksheet->write($row+$i, $col+19, 'Postpaid', $format);
$worksheet->write($row+$i, $col+20, 'Prepaid', $format);
$worksheet->write($row+$i, $col+21, 'TNT', $format);
$worksheet->write($row+$i, $col+22, 'Bro', $format);
$worksheet->write($row+$i, $col+23, 'TOTAL', $format);
$worksheet->write($row+$i, $col+24, 'Postpaid', $format);
$worksheet->write($row+$i, $col+25, 'Prepaid', $format);
$worksheet->write($row+$i, $col+26, 'TNT', $format);
$worksheet->write($row+$i, $col+27, 'Bro', $format);
$worksheet->write($row+$i, $col+28, 'TOTAL', $format);
$worksheet->write($row+$i, $col+29, 'TOTAL', $format);
$worksheet->write($row+$i, $col+30, 'Postpaid', $format);
$worksheet->write($row+$i, $col+31, 'Prepaid', $format);
$worksheet->write($row+$i, $col+32, 'TNT', $format);
$worksheet->write($row+$i, $col+33, 'Bro', $format);
#SUN
$worksheet->write($row+$i, $col+35, 'TOTAL', $format);
$worksheet->write($row+$i, $col+36, 'Postpaid', $format);
$worksheet->write($row+$i, $col+37, 'Prepaid', $format);
$worksheet->write($row+$i, $col+38, 'TOTAL', $format);
$worksheet->write($row+$i, $col+39, 'Postpaid', $format);
$worksheet->write($row+$i, $col+40, 'Prepaid', $format);
$worksheet->write($row+$i, $col+41, 'TOTAL', $format);
$worksheet->write($row+$i, $col+42, 'TOTAL', $format);
$worksheet->write($row+$i, $col+43, 'Postpaid', $format);
$worksheet->write($row+$i, $col+44, 'Prepaid', $format);
#REGISTRATION PER Carrier/SN
$worksheet->write($row+$i, $col+46, 'Globe', $format);
$worksheet->write($row+$i, $col+47, 'Smart', $format);
$worksheet->write($row+$i, $col+48, 'Sun', $format);
$worksheet->write($row+$i, $col+49, 'Facebook', $format);
$worksheet->write($row+$i, $col+50, 'Twitter', $format);
$worksheet->write($row+$i, $col+51, 'Google+', $format);
$worksheet->write($row+$i, $col+52, 'LinkedIN', $format);
#LOGIN PER Carrier/Device
$worksheet->write($row+$i, $col+54, 'Globe', $format);
$worksheet->write($row+$i, $col+55, 'Smart', $format);
$worksheet->write($row+$i, $col+56, 'Sun', $format);
$worksheet->write($row+$i, $col+57, 'Android', $format);
$worksheet->write($row+$i, $col+58, 'iOS', $format);
$worksheet->write($row+$i, $col+59, 'Web', $format);

my @rowRst;
while (@rowRst = $sth_ctm_v6->fetchrow()) {
   $i++;
   $worksheet->write($row+$i, $col, $rowRst[0], $format1);    
   $worksheet->write($row+$i, $col+1, $rowRst[1], $format1);  
   $worksheet->write($row+$i, $col+2, $rowRst[2], $format1);  
   $worksheet->write($row+$i, $col+3, $rowRst[3], $format1);  
   $worksheet->write($row+$i, $col+4, $rowRst[4], $format1);  
   $worksheet->write($row+$i, $col+5, $rowRst[5], $format1);  
   $worksheet->write($row+$i, $col+6, $rowRst[6], $format1);  
   $worksheet->write($row+$i, $col+7, $rowRst[7], $format1);  
   $worksheet->write($row+$i, $col+8, $rowRst[8], $format1);  
   $worksheet->write($row+$i, $col+9, $rowRst[9], $format1);  
   $worksheet->write($row+$i, $col+10, $rowRst[10], $format1);
   $worksheet->write($row+$i, $col+11, $rowRst[11], $format1);
   $worksheet->write($row+$i, $col+12, $rowRst[12], $format1);
   $worksheet->write($row+$i, $col+13, $rowRst[13], $format1);
   $worksheet->write($row+$i, $col+14, $rowRst[14], $format1);
   $worksheet->write($row+$i, $col+15, $rowRst[15], $format1);
   $worksheet->write($row+$i, $col+16, $rowRst[16], $format1);
   $worksheet->write($row+$i, $col+18, $rowRst[17], $format1);
   $worksheet->write($row+$i, $col+19, $rowRst[18], $format1);
   $worksheet->write($row+$i, $col+20, $rowRst[19], $format1);
   $worksheet->write($row+$i, $col+21, $rowRst[20], $format1);
   $worksheet->write($row+$i, $col+22, $rowRst[21], $format1);
   $worksheet->write($row+$i, $col+23, $rowRst[22], $format1);
   $worksheet->write($row+$i, $col+24, $rowRst[23], $format1);
   $worksheet->write($row+$i, $col+25, $rowRst[24], $format1);
   $worksheet->write($row+$i, $col+26, $rowRst[25], $format1);
   $worksheet->write($row+$i, $col+27, $rowRst[26], $format1);
   $worksheet->write($row+$i, $col+28, $rowRst[27], $format1);
   $worksheet->write($row+$i, $col+29, $rowRst[28], $format1);
   $worksheet->write($row+$i, $col+30, $rowRst[29], $format1);
   $worksheet->write($row+$i, $col+31, $rowRst[30], $format1);
   $worksheet->write($row+$i, $col+32, $rowRst[31], $format1);
   $worksheet->write($row+$i, $col+33, $rowRst[32], $format1);
   $worksheet->write($row+$i, $col+35, $rowRst[33], $format1);
   $worksheet->write($row+$i, $col+36, $rowRst[34], $format1);
   $worksheet->write($row+$i, $col+37, $rowRst[35], $format1);
   $worksheet->write($row+$i, $col+38, $rowRst[36], $format1);
   $worksheet->write($row+$i, $col+39, $rowRst[37], $format1);
   $worksheet->write($row+$i, $col+40, $rowRst[38], $format1);
   $worksheet->write($row+$i, $col+41, $rowRst[39], $format1);
   $worksheet->write($row+$i, $col+42, $rowRst[40], $format1);
   $worksheet->write($row+$i, $col+43, $rowRst[41], $format1);
   $worksheet->write($row+$i, $col+44, $rowRst[42], $format1);
   $worksheet->write($row+$i, $col+46, $rowRst[43], $format1);
   $worksheet->write($row+$i, $col+47, $rowRst[44], $format1);
   $worksheet->write($row+$i, $col+48, $rowRst[45], $format1);
   $worksheet->write($row+$i, $col+49, $rowRst[46], $format1);
   $worksheet->write($row+$i, $col+50, $rowRst[47], $format1);
   $worksheet->write($row+$i, $col+51, $rowRst[48], $format1);
   $worksheet->write($row+$i, $col+52, $rowRst[49], $format1);
   $worksheet->write($row+$i, $col+54, $rowRst[50], $format1);
   $worksheet->write($row+$i, $col+55, $rowRst[51], $format1);
   $worksheet->write($row+$i, $col+56, $rowRst[52], $format1);
   $worksheet->write($row+$i, $col+57, $rowRst[53], $format1);
   $worksheet->write($row+$i, $col+58, $rowRst[54], $format1);
   $worksheet->write($row+$i, $col+59, $rowRst[55], $format1);
}


	
$workbook->close();
 binmode STDOUT;

$from = "do-not-reply\@chikka.com";
$to = "glenon\@chikka.com";
$cc = "glenon\@chikka.com";
$Subject = "CTMV6 Stats , ".$current_day;

# Part using which the attachment is sent to an email #
$msg = MIME::Lite->new(
        From     => $from,
        To       => $to,
		Cc      => $cc,
        Subject  => $Subject,
        Type     => 'File/xls',
        Path     => $excel_file
);

    $msg->attach(
        Type => 'text/html',
        Data => qq{
            <body>
      		<p>
			<span style="font-size:14px;"><span style="font-family: Calibri, helvetica, sans-serif;">CTM V6 Stats for the Month of $txt_month.</span></span></p>
		<p>
			<span style="font-size:14px;"><span style="font-family: Calibri, helvetica, sans-serif;">Please refer to the attachment.</span></span></p>
		<p>
			&nbsp;</p>
		<div>
			<span style="font-size:14px;"><span style="font-family: Calibri, helvetica, sans-serif;">Regards,</span></span></div>
		<div>
			<span style="font-size:14px;"><span style="font-family: Calibri, helvetica, sans-serif;">CHIKKA DBA TEAM</span></span></div>
		<p>
			&nbsp;</p>
		<p>
			<br />
			&nbsp;</p>
            </body>
        },
    );
	
print "Mail Sent\n";
$msg->send; # send via default

